# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebot', '0003_auto_20180911_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_ref',
            field=models.UUIDField(editable=False),
        ),
    ]
