# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corebot', '0004_auto_20180911_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image_ref',
            field=models.CharField(max_length=32),
        ),
    ]
